name: Bug report
description: Create a bug report to help us improve.
labels: [ 'bug' ]

body:
  - type: checkboxes
    attributes:
      label: What module(s) is this issue related to?
      description: If you don't know, select all that were installed.
      options:
        - label: Anti-Xray `ply-anti-xray`
        - label: Common `ply-common`
        - label: Database `ply-database`
        - label: Locking `ply-locking`
        - label: Tracker `ply-tracker`
        - label: Miscallenious `plymouth`
        - label: Debug `ply-debug`

  - type: input
    attributes:
      label: Environment
      description: |
        What platform, side and version of Minecraft, Plymouth and Java are you using?

        Example:
          - **Minecraft**: 1.17 Server
          - **Plymouth**: 0.0.0-beta.5
          - **Loader**: Fabric
          - **Java**: AdoptOpenJDK 16.0.1
      value: |
        - **Minecraft**:
        - **Plymouth**:
        - **Mod Loader**:
        - **Java**:
    validations:
      required: true

  - type: textarea
    attributes:
      label: To reproduce
      description: Steps to reproduce the behaviour.
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true

  - type: input
    attributes:
      label: Expected results
      description: What behaviour did you expect?
      placeholder: e.g. To be wither immune.
    validations:
      required: true

  - type: input
    attributes:
      label: Actual results
      description: What behaviour did you observe instead?
      placeholder: e.g. The wither destroyed it.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: Crash reports, server logs, screenshots and videos should go here.
    validations:
      required: false