import javax.swing.*;
import java.awt.*;
import java.nio.file.Path;
import java.util.Objects;

public class Standalone {
    public static void main(final String[] args) {
        try {
            var os = System.getProperty("os.name").toLowerCase();
            var path = (os.startsWith("win") ?
                    Path.of(Objects.requireNonNullElse(System.getenv("APPDATA"), System.getProperty("user.home", ".")), ".minecraft", "mods") :
                    os.contains("mac") || os.contains("osx") ?
                            Path.of(System.getProperty("user.home", "."), "Library", "Application Support", "minecraft", "mods") :
                            Path.of(System.getProperty("user.home", "."), ".minecraft"));
            if (JOptionPane.showOptionDialog(null, "Please put Helium in your mods folder.\nIt'll be located at `" + path.toAbsolutePath().toString() + "`.\n\nWould you like that folder to be opened?", "Helium Mod", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null) == JOptionPane.YES_OPTION) {
                Desktop.getDesktop().browseFileDirectory(path.toFile());
            }
        } catch (Exception e) {
            System.out.println("======= Helium Mod =======");
            System.out.println("Please install Helium in the mods folder that has been generated by the server.");
            System.out.println("If the mods folder is not present, use `mkdir mods` to make one.");
        }
    }
}
