name: Publish release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v3
        with:
          distribution: termurin
          java-version: 17
      - name: Build and publish with Gradle
        run: ./gradlew build publish poolBuilds --no-daemon
        env:
          BUILD_RELEASE: ${{github.event.prelease == false}}
          MODRINTH_TOKEN: ${{secrets.MODRINTH}}
          CHANGELOG: ${{ github.event.release.body }}
      - name: Upload build artifacts
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/pool/*'
          repo-token: ${{secrets.GITHUB_TOKEN}}